---
title: "COT Leveraged Positions Analysis"
author: "Greg Winkler"
date: '`r format(Sys.Date(), "%B %d, %Y")`'
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE, warning=FALSE, message=FALSE}

knitr::opts_chunk$set(echo = TRUE)

library(RMongo)
library(ggplot2)
library(dplyr)
library(tidyr)
library(lubridate)
library(scales)


mgdb <- mongoDbConnect('cftc', 'localhost', 27017)

cotDB <- dbGetQuery(mgdb, "cot_financial", 
                      '{"FutOnly_or_Combined": "Combined"}', 
                      skip=0, limit=Inf)
cotDB <- cotDB %>% separate(Market_and_Exchange_Names, 
                                c('Contract', 'Exchange'), sep = ' - ')
contracts <- cotDB %>% select(Contract) %>% distinct()
cotDB$Report_Date_as_YYYY_MM_DD <- as.POSIXct(strptime(cotDB$Report_Date_as_YYYY_MM_DD,
                                                         "%Y-%m-%d"))

cotDB$Lev_Money_Net <- cotDB$Lev_Money_Positions_Long_All - 
                            cotDB$Lev_Money_Positions_Short_All

```

```{r echo=FALSE, warning=FALSE, message=FALSE}

contractName = "U.S. DOLLAR INDEX"
ggplot(subset(cotDB, Contract == contractName), 
              aes(x = Report_Date_as_YYYY_MM_DD, y = Lev_Money_Net)) +
  geom_line() + 
  geom_hline(yintercept = 0, linetype=2, color = 'red') +
  scale_x_datetime(xlab("Date")) +
  scale_y_continuous(ylab("Net Leveraged Position"), labels = comma) +
  ggtitle(contractName) +
  theme(plot.title = element_text(hjust = 0.5, size = 18))

```

```{r echo=FALSE, warning=FALSE, message=FALSE}

contractName = "EURO FX"
ggplot(subset(cotDB, Contract == contractName), 
              aes(x = Report_Date_as_YYYY_MM_DD, y = Lev_Money_Net)) +
  geom_line() + 
  geom_hline(yintercept = 0, linetype=2, color = 'red') +
  scale_x_datetime(xlab("Date")) +
  scale_y_continuous(ylab("Net Leveraged Position"), labels = comma) +
  ggtitle(contractName) +
  theme(plot.title = element_text(hjust = 0.5, size = 18))

```

```{r echo=FALSE, warning=FALSE, message=FALSE}

contractName = "BRITISH POUND STERLING"
ggplot(subset(cotDB, Contract == contractName), 
              aes(x = Report_Date_as_YYYY_MM_DD, y = Lev_Money_Net)) +
  geom_line() + 
  geom_hline(yintercept = 0, linetype=2, color = 'red') +
  scale_x_datetime(xlab("Date")) +
  scale_y_continuous(ylab("Net Leveraged Position"), labels = comma) +
  ggtitle(contractName) +
  theme(plot.title = element_text(hjust = 0.5, size = 18))

```

```{r echo=FALSE, warning=FALSE, message=FALSE}

contractName = "JAPANESE YEN"
ggplot(subset(cotDB, Contract == contractName), 
              aes(x = Report_Date_as_YYYY_MM_DD, y = Lev_Money_Net)) +
  geom_line() + 
  geom_hline(yintercept = 0, linetype=2, color = 'red') +
  scale_x_datetime(xlab("Date")) +
  scale_y_continuous(ylab("Net Leveraged Position"), labels = comma) +
  ggtitle(contractName) +
  theme(plot.title = element_text(hjust = 0.5, size = 18))

```

```{r echo=FALSE, warning=FALSE, message=FALSE}

contractName = "CANADIAN DOLLAR"
ggplot(subset(cotDB, Contract == contractName), 
              aes(x = Report_Date_as_YYYY_MM_DD, y = Lev_Money_Net)) +
  geom_line() + 
  geom_hline(yintercept = 0, linetype=2, color = 'red') +
  scale_x_datetime(xlab("Date")) +
  scale_y_continuous(ylab("Net Leveraged Position"), labels = comma) +
  ggtitle(contractName) +
  theme(plot.title = element_text(hjust = 0.5, size = 18))

```

```{r echo=FALSE, warning=FALSE, message=FALSE}

contractName = "AUSTRALIAN DOLLAR"
ggplot(subset(cotDB, Contract == contractName), 
              aes(x = Report_Date_as_YYYY_MM_DD, y = Lev_Money_Net)) +
  geom_line() + 
  geom_hline(yintercept = 0, linetype=2, color = 'red') +
  scale_x_datetime(xlab("Date")) +
  scale_y_continuous(ylab("Net Leveraged Position"), labels = comma) +
  ggtitle(contractName) +
  theme(plot.title = element_text(hjust = 0.5, size = 18))

```

```{r echo=FALSE, warning=FALSE, message=FALSE}

contractName = "NEW ZEALAND DOLLAR"
ggplot(subset(cotDB, Contract == contractName), 
              aes(x = Report_Date_as_YYYY_MM_DD, y = Lev_Money_Net)) +
  geom_line() + 
  geom_hline(yintercept = 0, linetype=2, color = 'red') +
  scale_x_datetime(xlab("Date")) +
  scale_y_continuous(ylab("Net Leveraged Position"), labels = comma) +
  ggtitle(contractName) +
  theme(plot.title = element_text(hjust = 0.5, size = 18))

```

```{r echo=FALSE, warning=FALSE, message=FALSE}

contractName = "E-MINI S&P 500 STOCK INDEX"
ggplot(subset(cotDB, Contract == contractName), 
              aes(x = Report_Date_as_YYYY_MM_DD, y = Lev_Money_Net)) +
  geom_line() + 
  geom_hline(yintercept = 0, linetype=2, color = 'red') +
  scale_x_datetime(xlab("Date")) +
  scale_y_continuous(ylab("Net Leveraged Position"), labels = comma) +
  ggtitle(contractName) +
  theme(plot.title = element_text(hjust = 0.5, size = 18))

```

```{r echo=FALSE, warning=FALSE, message=FALSE}

contractName = "VIX FUTURES"
ggplot(subset(cotDB, Contract == contractName), 
              aes(x = Report_Date_as_YYYY_MM_DD, y = Lev_Money_Net)) +
  geom_line() + 
  geom_hline(yintercept = 0, linetype=2, color = 'red') +
  scale_x_datetime(xlab("Date")) +
  scale_y_continuous(ylab("Net Leveraged Position"), labels = comma) +
  ggtitle(contractName) +
  theme(plot.title = element_text(hjust = 0.5, size = 18))

```

```{r echo=FALSE, warning=FALSE, message=FALSE}

contractName = "3-MONTH EURODOLLARS"
ggplot(subset(cotDB, Contract == contractName), 
              aes(x = Report_Date_as_YYYY_MM_DD, y = Lev_Money_Net)) +
  geom_line() + 
  geom_hline(yintercept = 0, linetype=2, color = 'red') +
  scale_x_datetime(xlab("Date")) +
  scale_y_continuous(ylab("Net Leveraged Position"), labels = comma) +
  ggtitle(contractName) +
  theme(plot.title = element_text(hjust = 0.5, size = 18))

```

```{r echo=FALSE, warning=FALSE, message=FALSE}

contractName = "2-YEAR U.S. TREASURY NOTES"
ggplot(subset(cotDB, Contract == contractName), 
              aes(x = Report_Date_as_YYYY_MM_DD, y = Lev_Money_Net)) +
  geom_line() + 
  geom_hline(yintercept = 0, linetype=2, color = 'red') +
  scale_x_datetime(xlab("Date")) +
  scale_y_continuous(ylab("Net Leveraged Position"), labels = comma) +
  ggtitle(contractName) +
  theme(plot.title = element_text(hjust = 0.5, size = 18))

```

```{r echo=FALSE, warning=FALSE, message=FALSE}

contractName = "5-YEAR U.S. TREASURY NOTES"
ggplot(subset(cotDB, Contract == contractName), 
              aes(x = Report_Date_as_YYYY_MM_DD, y = Lev_Money_Net)) +
  geom_line() + 
  geom_hline(yintercept = 0, linetype=2, color = 'red') +
  scale_x_datetime(xlab("Date")) +
  scale_y_continuous(ylab("Net Leveraged Position"), labels = comma) +
  ggtitle(contractName) +
  theme(plot.title = element_text(hjust = 0.5, size = 18))

```

```{r echo=FALSE, warning=FALSE, message=FALSE}

contractName = "10-YEAR U.S. TREASURY NOTES"
ggplot(subset(cotDB, Contract == contractName), 
              aes(x = Report_Date_as_YYYY_MM_DD, y = Lev_Money_Net)) +
  geom_line() + 
  geom_hline(yintercept = 0, linetype=2, color = 'red') +
  scale_x_datetime(xlab("Date")) +
  scale_y_continuous(ylab("Net Leveraged Position"), labels = comma) +
  ggtitle(contractName) +
  theme(plot.title = element_text(hjust = 0.5, size = 18))

```

```{r echo=FALSE, warning=FALSE, message=FALSE}

contractName = "U.S. TREASURY BONDS"
ggplot(subset(cotDB, Contract == contractName), 
              aes(x = Report_Date_as_YYYY_MM_DD, y = Lev_Money_Net)) +
  geom_line() + 
  geom_hline(yintercept = 0, linetype=2, color = 'red') +
  scale_x_datetime(xlab("Date")) +
  scale_y_continuous(ylab("Net Leveraged Position"), labels = comma) +
  ggtitle(contractName) +
  theme(plot.title = element_text(hjust = 0.5, size = 18))

```

All data is from the CFTC Commitments of Traders Report:  http://www.cftc.gov/MarketReports/CommitmentsofTraders/index.htm
